sudo docker tag $SEMAPHORE_PROJECT_NAME:latest $DOCKER_REPO:build-$BRANCH_NAME-$SEMAPHORE_BUILD_NUMBER
DOCKER_LOGIN="$(aws ecr get-login --region $AWS_DEFAULT_REGION)"
eval $DOCKER_LOGIN
sudo docker push $DOCKER_REPO:build-$BRANCH_NAME-$SEMAPHORE_BUILD_NUMBER